# SPDX-License-Identifier: 0BSD

[workspace]
members = [
  "rust/crates/rusticol-core",
  "rust/crates/rusticol-python",
  "rust/crates/rusticol-capi",
]
exclude = [
  "TMP_FIXED_SYMJIT",
  "TMP_FIXED_SPENSO",
]
resolver = "2"

[workspace.package]
version = "0.2.1"
edition = "2024"
rust-version = "1.89.0"
license = "0BSD"
authors = [
  "Rikkert Frederix <rikkert.frederix@thep.lu.se>",
  "Valentin Hirschi <valentin.hirschi@gmail.com>",
  "Timea Vitos <timea.vitos@thep.lu.se>",
]
repository = "https://github.com/mg5amcnlo/pyamplicol"

[workspace.dependencies]
bincode = { version = "2.0", features = ["serde"] }
flate2 = "1.1"
libc = "0.2"
numpy = "0.29"
num-bigint = "0.4"
num-rational = "0.4"
num-traits = "0.2"
pyo3 = { version = "0.29", features = ["abi3-py311"] }
rayon = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["float_roundtrip", "raw_value"] }
sha2 = "0.10"
symbolica = { version = "=2.2.0", default-features = true, features = ["bincode"] }
thiserror = "2.0"
wide = "1.7"

[patch.crates-io]
symbolica = { git = "https://github.com/symbolica-dev/symbolica.git", rev = "0084bc7c1418940fdec652059cd704e00d07e9d1" }
numerica = { git = "https://github.com/symbolica-dev/symbolica.git", rev = "0084bc7c1418940fdec652059cd704e00d07e9d1" }
graphica = { git = "https://github.com/symbolica-dev/symbolica.git", rev = "0084bc7c1418940fdec652059cd704e00d07e9d1" }
symjit = { path = "./TMP_FIXED_SYMJIT" }
spenso = { path = "./TMP_FIXED_SPENSO/crates/spenso" }
spenso-hep-lib = { path = "./TMP_FIXED_SPENSO/crates/spenso-hep-lib" }
spenso-macros = { path = "./TMP_FIXED_SPENSO/crates/spenso-macros" }
spynso3 = { path = "./TMP_FIXED_SPENSO/crates/spynso3" }
idenso = { path = "./TMP_FIXED_SPENSO/crates/idenso" }
linnet = { path = "./TMP_FIXED_SPENSO/crates/linnet" }
symbolica-utils = { path = "./TMP_FIXED_SPENSO/crates/symbolica-utils" }
vakint = { path = "./TMP_FIXED_SPENSO/crates/vakint" }
symbolica-integrate = { path = "./TMP_FIXED_SPENSO/symbolica-integrate" }

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
panic = "unwind"
strip = "debuginfo"
