[package]
name = "compressed-success-status"
version = "0.0.0"
edition = "2021"

[workspace]

[dependencies]
anyhow = "1"
symjit = { git = "https://github.com/siravan/symjit-crate.git", rev = "f1c193d301897149de6609f706297b0c97a4f018", default-features = false }

[[test]]
name = "mre"
path = "mre.rs"
