# SPDX-License-Identifier: 0BSD

from collections.abc import Mapping, Sequence
from os import PathLike
from typing import Literal, TypeAlias

ScalarInput: TypeAlias = float | int
Momenta: TypeAlias = Sequence[Sequence[Sequence[ScalarInput]]]
ModelParameterValue: TypeAlias = complex | float | int
ResolvedScalar: TypeAlias = float
RuntimeProfile: TypeAlias = Mapping[str, object]

class TargetInfo:
    @property
    def triple(self) -> str: ...
    @property
    def cpu_features(self) -> list[str]: ...

class RusticolError(Exception): ...
class ArtifactError(RusticolError): ...
class CompatibilityError(RusticolError): ...
class EvaluationError(RusticolError): ...
class SelectorError(EvaluationError): ...
class ModelParameterError(EvaluationError): ...

class ExternalParticle:
    @property
    def index(self) -> int: ...
    @property
    def label(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def pdg_id(self) -> int: ...
    @property
    def state(self) -> Literal["incoming", "outgoing"]: ...
    @property
    def momentum_slot(self) -> int: ...

class HelicityConfiguration:
    @property
    def id(self) -> str: ...
    @property
    def index(self) -> int: ...
    @property
    def values(self) -> list[int]: ...
    @property
    def computed(self) -> bool: ...
    @property
    def structural_zero(self) -> bool: ...
    @property
    def representative_id(self) -> str: ...
    @property
    def coefficient(self) -> float: ...

class ColorFlow:
    @property
    def id(self) -> str: ...
    @property
    def index(self) -> int: ...
    @property
    def word(self) -> list[int]: ...
    @property
    def computed(self) -> bool: ...
    @property
    def representative_id(self) -> str: ...
    @property
    def coefficient(self) -> float: ...

class ContractedColorComponent:
    @property
    def id(self) -> str: ...
    @property
    def index(self) -> int: ...
    @property
    def description(self) -> str: ...

class ModelParameter:
    @property
    def name(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def default_real(self) -> float: ...
    @property
    def default_imaginary(self) -> float: ...
    @property
    def mutable(self) -> bool: ...

class ReductionGroup:
    @property
    def id(self) -> str: ...
    @property
    def representative_helicity_id(self) -> str: ...
    @property
    def representative_color_id(self) -> str: ...
    @property
    def physical_helicity_ids(self) -> list[str]: ...
    @property
    def physical_color_ids(self) -> list[str]: ...

class PhysicsReduction:
    @property
    def kind(self) -> Literal["lc-diagonal", "contracted-color"]: ...
    @property
    def groups(self) -> list[ReductionGroup]: ...

class ProcessPhysics:
    @property
    def process_id(self) -> str: ...
    @property
    def process(self) -> str: ...
    @property
    def color_accuracy(self) -> Literal["lc", "nlc", "full"]: ...
    @property
    def helicity_coverage(self) -> str: ...
    @property
    def color_coverage(self) -> str: ...
    @property
    def color_kind(self) -> str: ...
    @property
    def structural_zero_helicity_count(self) -> int: ...
    @property
    def external_particles(self) -> list[ExternalParticle]: ...
    @property
    def helicities(self) -> list[HelicityConfiguration]: ...
    @property
    def color_flows(self) -> list[ColorFlow]: ...
    @property
    def contracted_color_components(self) -> list[ContractedColorComponent]: ...
    @property
    def reduction(self) -> PhysicsReduction: ...
    @property
    def model_parameters(self) -> list[ModelParameter]: ...
    @property
    def selector_capabilities(self) -> list[str]: ...

class ResolvedEvaluation:
    @property
    def values(self) -> list[list[list[ResolvedScalar]]]: ...
    @property
    def shape(self) -> tuple[int, int, int]: ...
    @property
    def helicity_ids(self) -> list[str]: ...
    @property
    def color_ids(self) -> list[str]: ...
    @property
    def color_flow_ids(self) -> list[str]: ...
    @property
    def color_accuracy(self) -> Literal["lc", "nlc", "full"]: ...
    @property
    def precision(self) -> int: ...
    def total(self) -> list[ResolvedScalar]: ...

class Runtime:
    def __init__(
        self,
        artifact: str | PathLike[str],
        *,
        process: str | None = None,
        model_parameters: Mapping[str, ModelParameterValue] | None = None,
        mute_warnings: bool = False,
    ) -> None: ...
    @staticmethod
    def load(
        artifact: str | PathLike[str],
        *,
        process: str | None = None,
        model_parameters: Mapping[str, ModelParameterValue] | None = None,
        mute_warnings: bool = False,
    ) -> Runtime: ...
    @property
    def process(self) -> str: ...
    @property
    def process_id(self) -> str: ...
    @property
    def color_accuracy(self) -> Literal["lc", "nlc", "full"]: ...
    @property
    def physics(self) -> ProcessPhysics: ...
    def metadata_json(self) -> str: ...
    def physics_json(self) -> str: ...
    def evaluate(
        self,
        momenta: Momenta,
        *,
        helicities: Sequence[str] | None = None,
        color_flows: Sequence[str] | None = None,
        precision: Literal[16] = 16,
    ) -> list[float]: ...
    def profile(
        self,
        momenta: Momenta,
        *,
        helicities: Sequence[str] | None = None,
        color_flows: Sequence[str] | None = None,
        precision: Literal[16] = 16,
        include_values: bool = False,
    ) -> RuntimeProfile: ...
    def evaluate_profile(
        self,
        momenta: Momenta,
        *,
        helicities: Sequence[str] | None = None,
        color_flows: Sequence[str] | None = None,
        precision: Literal[16] = 16,
        include_values: bool = False,
    ) -> RuntimeProfile: ...
    def evaluate_resolved(
        self,
        momenta: Momenta,
        *,
        helicities: Sequence[str] | None = None,
        color_flows: Sequence[str] | None = None,
        precision: Literal[16] = 16,
    ) -> ResolvedEvaluation: ...
    def evaluate_with_prec(
        self, momenta: Momenta, decimal_digit_precision: Literal[16]
    ) -> list[float]: ...
    def evaluate_resolved_with_prec(
        self,
        momenta: Momenta,
        decimal_digit_precision: Literal[16],
        helicities: Sequence[str] | None = None,
        color_flows: Sequence[str] | None = None,
    ) -> ResolvedEvaluation: ...
    def set_model_parameters(
        self, mapping: Mapping[str, ModelParameterValue]
    ) -> None: ...
    def set_model_parameter(self, name: str, value: ModelParameterValue) -> None: ...
    def mute_warnings(self) -> None: ...
    def unmute_warnings(self) -> None: ...
    def take_warnings(self) -> list[str]: ...

def abi_version() -> int: ...
def package_version() -> str: ...
def target_info() -> TargetInfo: ...
