# SPDX-License-Identifier: 0BSD
"""Strict typed reference-physics fixture reader."""

from .api import load_reference_fixture, parse_reference_fixture
from .codec import (
    _parse_point,
    _validate_evidence_record_hashes,
    _validate_physics_case_hashes,
    _validate_reduction_plan_hashes,
    _validate_wire,
    evidence_record_sha256,
    physics_case_sha256,
    reduction_plan_sha256,
)
from .model import (
    ColorAxis,
    ComplexDecimal,
    ContractedColorComponent,
    Coverage,
    DependencyProvenance,
    FixtureProvenance,
    HelicityAxis,
    LCColorFlow,
    ModelProvenance,
    Normalization,
    Observation,
    OracleEvidence,
    OracleEvidenceSet,
    OracleProvenance,
    PointAlgorithm,
    Process,
    ProcessIdentity,
    Reduction,
    ReductionGroup,
    ReferenceCase,
    ReferenceFixture,
    ReferenceFixtureError,
    ReferencePoint,
    Selectors,
    StressMetric,
    Tolerances,
    Topology,
)
from .numerics import _within_tolerance

__all__ = [
    "ColorAxis",
    "ComplexDecimal",
    "ContractedColorComponent",
    "Coverage",
    "DependencyProvenance",
    "FixtureProvenance",
    "HelicityAxis",
    "LCColorFlow",
    "ModelProvenance",
    "Normalization",
    "Observation",
    "OracleEvidence",
    "OracleEvidenceSet",
    "OracleProvenance",
    "PointAlgorithm",
    "Process",
    "ProcessIdentity",
    "Reduction",
    "ReductionGroup",
    "ReferenceCase",
    "ReferenceFixture",
    "ReferenceFixtureError",
    "ReferencePoint",
    "Selectors",
    "StressMetric",
    "Tolerances",
    "Topology",
    "_parse_point",
    "_validate_evidence_record_hashes",
    "_validate_physics_case_hashes",
    "_validate_reduction_plan_hashes",
    "_validate_wire",
    "_within_tolerance",
    "evidence_record_sha256",
    "load_reference_fixture",
    "parse_reference_fixture",
    "physics_case_sha256",
    "reduction_plan_sha256",
]
